title = "gogdl-ng"

[application]
# Defines the port on which the application is listening for requests.
listenPort = 3200

# Defines the location where to write the application log file.
logFilePath = "./config/gogdl-ng.log"

[queue]
# Defines the maximum capacity of the job queue.
size = 1000

# Defines how many workers can run concurrently.
maxWorkers = 5

[download]
# Defines how many times a failed download should be retried.
retryThreeshold = 5

