title = "gogdl-ng"

[application]
# Defines the port on which the application is listening for requests.
listenPort = 3200

[logging]
# Defines the log level. Must be one of the following: trace, debug, info, warn, error, fatal, panic
logLevel = "info"

# Defines the location where to write the application log file.
logFilePath = "./config/gogdl-ng.log"

# Defines if the messages should also be logged to console or not
logToConsole = true

[queue]
# Defines the maximum capacity of the job queue.
size = 1000

# Defines how many workers can run concurrently.
maxWorkers = 2

[gdrive]
# query string which will be appended to the base query which is: "'%drive_folder_id%' in parents and"
query = "trashed=false"

[download]
# Defines how many times a failed download should be retried.
retryThreeshold = 5

